version: '3.9'

services:
  praxeo-db:
    image: postgres:15
    container_name: praxeo-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - praxeo-net

  praxeo-backend:
    build: ./praxeo-backend
    container_name: praxeo-backend
    restart: always
    depends_on:
      - praxeo-db

    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://praxeo-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      SPRING_MAIL_DEFAULT_ENCODING: ${SPRING_MAIL_DEFAULT_ENCODING}
      SPRING_MAIL_TEST_CONNECTION: ${SPRING_MAIL_TEST_CONNECTION}

      UNIVERSITY_EMAIL_DOMAIN: ${UNIVERSITY_EMAIL_DOMAIN}

      FRONTEND_URL: http://localhost:5173

    ports:
      - "8080:8080"
    networks:
      - praxeo-net

  praxeo-frontend:
    build:
      context: ./praxeo-frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}

    environment:
      - VITE_API_BASE_URL=http://praxeo-backend:8080/api

    container_name: praxeo-frontend
    restart: always

    ports:
      - "5173:80"

    depends_on:
      - praxeo-backend

    networks:
      - praxeo-net

networks:
  praxeo-net:
    driver: bridge
